window.demoWhatsappLinks = {
  "dilma-santana-podologa": {
    "phone": "5527999732860",
    "message": "Perfeito, Dilma. Montei uma prévia simples para você visualizar:\n\nhttps://portifolio-luizfbm.com.br/demos/dilma-santana-podologa/\n\nNão é uma versão final ainda. Usei só informações públicas da sua agenda e do Instagram para mostrar como seu atendimento poderia ficar organizado fora do portal, com apresentação, serviços, localização, agenda e botão direto para WhatsApp.\n\nSe fizer sentido, eu ajusto com você os textos, cores, serviços e informações para deixar com a sua cara."
  },
  "betafisio": {
    "phone": "5527997417152",
    "message": "Oi, pessoal da Betafisio. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Betafisio pesquisando clínicas de fisioterapia e pilates em Vila Velha e preparei uma prévia de site para vocês.\n\nFiz isso porque, quando alguém procura uma clínica pelo celular, essa pessoa decide rápido se vai chamar ou continuar procurando. Um site próprio ajuda a mostrar o que a Betafisio faz, onde atende e como falar pelo WhatsApp sem depender só de Instagram, diretórios ou links soltos.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/betafisio/\n\nNão é o modelo final. É uma proposta visual inicial para vocês verem o potencial. Posso ajustar textos, cores, fotos, serviços, ordem das seções e tudo que fizer mais sentido para a rotina da Betafisio.\n\nUsei apenas informações públicas e imagens neutras. Não usei fotos privadas, pacientes nem promessas de resultado. A intenção é mostrar como um site simples e bem feito poderia deixar a Betafisio mais fácil de encontrar, entender e chamar.\n\nSe vocês gostarem da ideia, posso conversar com vocês, entender melhor o negócio e transformar essa prévia em um site real, com a cara da Betafisio e focado em gerar contato pelo WhatsApp.\n\nPosso te explicar como funcionaria?"
  },
  "center-pilates-fisioterapia": {
    "phone": "5527998081804",
    "message": "Oi, pessoal da Center Pilates & Fisioterapia. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Center pesquisando pilates e fisioterapia em Vila Velha e montei uma prévia de site para vocês verem.\n\nPensei nisso porque muita gente decide pelo celular: abre o Google, olha duas ou três opções e chama quem passa mais confiança mais rápido. Uma página própria ajuda a mostrar que vocês atendem em Ataíde, explicar o básico do serviço e levar a pessoa direto para o WhatsApp.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/center-pilates-fisioterapia/\n\nNão é o modelo final. É um ponto de partida para vocês avaliarem. Posso ajustar texto, cores, fotos, serviços, horários e a ordem das informações conforme o funcionamento real da Center.\n\nUsei apenas informações públicas e imagem neutra. Não usei fotos do espaço, alunos, pacientes ou promessa de resultado. A ideia é mostrar como um site simples pode deixar o contato mais fácil e profissional.\n\nSe fizer sentido para vocês, posso entender melhor a rotina do estúdio e transformar essa prévia em um site pronto para receber contatos pelo WhatsApp.\n\nPosso te mostrar como ficaria esse processo?"
  },
  "ceo-clinica-especialidades-odontologicas": {
    "phone": "552732278122",
    "message": "Oi, pessoal da CEO Clínica de Especialidades Odontológicas. Tudo bem?\n\nSou Luiz, de Vitória. Encontrei a CEO em fontes públicas e preparei uma prévia de site pensando em uma clínica odontológica que precisa passar confiança logo no primeiro acesso.\n\nHoje, quando alguém procura atendimento odontológico, geralmente quer três coisas rápido: saber se encontrou a clínica certa, entender onde fica e conseguir chamar sem procurar telefone em vários lugares. Uma página própria resolve esse caminho com mais clareza.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/ceo-clinica-especialidades-odontologicas/\n\nNão é o modelo final. É uma proposta inicial para vocês avaliarem. Posso ajustar especialidades, textos, imagens autorizadas, cores, localização, botões e tudo que precisar para representar melhor a CEO.\n\nUsei apenas informações públicas. Não usei fotos privadas, pacientes, antes e depois ou promessas de resultado. Também não tratei listas de procedimentos de diretório como informação oficial sem confirmação.\n\nSe vocês gostarem da direção, posso conversar com vocês, entender o que a clínica quer destacar e transformar essa prévia em um site real, mais organizado e focado em contato.\n\nPosso te explicar a ideia com mais detalhes?"
  },
  "clifit": {
    "phone": "5527988273408",
    "message": "Oi, pessoal da CLIFIT. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a CLIFIT pesquisando fisioterapia e terapia ocupacional em Vila Velha e fiz uma prévia de site para mostrar como a clínica poderia aparecer melhor fora das redes sociais.\n\nA pessoa que chega pelo celular costuma decidir em poucos segundos se vai chamar ou continuar pesquisando. Um site próprio ajuda a organizar os serviços, a região de atendimento e o WhatsApp em uma experiência mais direta.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/clifit/\n\nNão é o modelo final. É uma primeira proposta visual. Posso ajustar texto, tom, cores, fotos, serviços, prioridades e a ordem das seções junto com vocês.\n\nUsei apenas informações públicas e uma imagem neutra. Não usei fotos de pacientes, conteúdo privado ou promessas de resultado. A intenção é vender melhor a primeira impressão da CLIFIT para quem ainda está decidindo se entra em contato.\n\nSe fizer sentido, posso conversar com vocês sobre a rotina da clínica e deixar essa página pronta para funcionar como site oficial.\n\nPosso te mostrar como eu faria esses ajustes?"
  },
  "clinica-equilibrio-fisioterapia": {
    "phone": "552732351857",
    "message": "Oi, pessoal da Clínica Equilíbrio. Tudo bem?\n\nSou Luiz, de Vitória. Encontrei a Clínica Equilíbrio pesquisando fisioterapia na região e preparei uma prévia de site com foco em clareza, confiança e contato rápido.\n\nQuando alguém procura fisioterapia, principalmente pelo celular, a página precisa responder logo: quem atende, onde fica, como falar e o que a pessoa pode esperar da primeira conversa. Hoje essas informações aparecem de forma mais espalhada.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/clinica-equilibrio-fisioterapia/\n\nNão é o modelo final. É uma proposta para vocês visualizarem o potencial. Posso ajustar textos, identidade visual, fotos autorizadas, serviços, endereço confirmado e todos os detalhes importantes para a clínica.\n\nUsei informações públicas e imagens neutras. Não usei fotos de pacientes, conteúdo privado ou promessas de resultado. A página foi pensada para comunicar com cuidado sem exagerar em promessa clínica.\n\nSe vocês gostarem da ideia, posso conversar com vocês e transformar essa prévia em um site real, com uma comunicação mais forte e focada em WhatsApp.\n\nPosso te explicar como isso funcionaria?"
  },
  "clinica-restaurar-fisioterapia-pilates": {
    "phone": "5527999486852",
    "message": "Oi, pessoal da Clínica Restaurar Fisioterapia e Pilates. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Restaurar pesquisando fisioterapia e pilates em Vila Velha e criei uma prévia de site para vocês avaliarem.\n\nPensei em uma página que ajude quem está em Terra Vermelha ou região a entender rápido que encontrou a clínica certa, ver o tipo de atendimento e chamar pelo WhatsApp sem precisar caçar informação em vários lugares.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/clinica-restaurar-fisioterapia-pilates/\n\nNão é o modelo final. É uma proposta inicial. Posso mudar textos, cores, fotos, serviços, horários, abordagem e qualquer detalhe que precise combinar melhor com a Restaurar.\n\nUsei apenas informações públicas e imagens neutras. Não usei fotos da clínica, pacientes, equipe ou promessas de resultado. A intenção é mostrar uma presença online mais clara, com cara de negócio local profissional.\n\nSe fizer sentido para vocês, posso entender melhor a rotina da clínica e transformar essa demonstração em um site pronto para gerar conversas pelo WhatsApp.\n\nPosso te passar como seria o próximo passo?"
  },
  "clinica-viva-sem-dor": {
    "phone": "5527998105020",
    "message": "Oi, pessoal da Clínica Viva Sem Dor. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a clínica pesquisando fisioterapia em Vila Velha e preparei uma prévia de site para mostrar como vocês poderiam ter uma presença própria mais forte.\n\nUma página bem organizada ajuda a pessoa que está pesquisando pelo celular a entender onde vocês atendem, qual é o caminho de contato e por que vale chamar a clínica antes de continuar procurando outras opções.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/clinica-viva-sem-dor/\n\nNão é o modelo final. É uma proposta visual inicial. Posso ajustar copy, cores, fotos autorizadas, serviços, estrutura e qualquer informação que vocês quiserem destacar.\n\nUsei só dados públicos e imagens neutras. Não usei fotos privadas, pacientes ou promessas de resultado. O cuidado aqui foi mostrar valor sem forçar afirmações clínicas que precisam de confirmação.\n\nSe vocês gostarem da ideia, posso conversar com vocês e montar uma versão final com a cara da clínica, pensada para transformar visitas em contatos pelo WhatsApp.\n\nPosso te explicar melhor a proposta?"
  },
  "coi-odontologia": {
    "phone": "5527996105491",
    "message": "Oi, pessoal da COI. Tudo bem?\n\nSou Luiz, de Vitória. Encontrei a COI pesquisando clínicas odontológicas e preparei uma prévia de site para mostrar como as informações de vocês poderiam ficar mais organizadas e comerciais.\n\nPara odontologia, a primeira impressão pesa muito. Quem pesquisa pelo celular quer confirmar se a clínica é confiável, entender quais áreas atende e chamar sem perder tempo em diretórios ou perfis soltos.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/coi-odontologia/\n\nNão é o modelo final. É uma base para conversa. Posso ajustar textos, especialidades confirmadas, fotos autorizadas, cores, endereço, WhatsApp e a ordem das informações com vocês.\n\nUsei apenas informações públicas. Não usei fotos de pacientes, conteúdo privado, antes e depois ou promessa de resultado odontológico. O objetivo é mostrar uma página própria mais clara, segura e pronta para contato.\n\nSe fizer sentido, posso entender melhor a COI e transformar essa prévia em um site real para fortalecer a presença online da clínica.\n\nPosso te mostrar como eu conduziria isso?"
  },
  "dentista-do-trabalhador": {
    "phone": "5527999473831",
    "message": "Oi, pessoal do Dentista do Trabalhador. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei o Dentista do Trabalhador em canais públicos e montei uma prévia de site pensando em quem procura atendimento odontológico na Glória pelo celular.\n\nHoje, um site próprio pode fazer diferença na decisão da primeira conversa. Ele mostra o nome da clínica, localização, WhatsApp e informações iniciais sem deixar o paciente depender só de Instagram ou Facebook.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/dentista-do-trabalhador/\n\nNão é o modelo final. É uma proposta inicial para vocês avaliarem. Posso ajustar textos, fotos autorizadas, cores, serviços, chamadas e tudo que precisar para representar melhor o consultório.\n\nUsei dados públicos e imagem neutra. Não usei fotos privadas, pacientes, antes e depois ou promessas de resultado. A página foi feita para vender clareza e facilitar o contato.\n\nSe vocês gostarem do caminho, posso conversar com vocês e transformar essa ideia em um site real, direto e focado em WhatsApp.\n\nPosso te explicar como seria?"
  },
  "ec-fisioterapia": {
    "phone": "5527988815456",
    "message": "Oi, pessoal da EC Fisioterapia. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a EC pesquisando fisioterapia e pilates em Vila Velha e preparei uma prévia de site para vocês verem como uma página própria poderia funcionar.\n\nQuem pesquisa pelo celular costuma comparar rápido. Se a informação aparece clara, com bairro, serviços e botão de WhatsApp, a chance de a pessoa iniciar conversa aumenta. Foi esse caminho que eu tentei montar na prévia.\n\nA página está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/ec-fisioterapia/\n\nNão é o modelo final. É uma proposta visual. Posso ajustar texto, fotos, cores, serviços, horários, localização e qualquer detalhe que precise ficar fiel ao atendimento real da EC.\n\nUsei apenas informações públicas e imagens neutras. Não usei fotos privadas, pacientes ou promessas de resultado. Alguns dados aparecem com cuidado justamente porque precisam ser confirmados antes de um site oficial.\n\nSe fizer sentido para vocês, posso entender melhor o negócio e transformar essa prévia em um site simples, profissional e pronto para receber contatos.\n\nPosso te mostrar o próximo passo?"
  },
  "equipe-fisioterapia-especializada": {
    "phone": "552733298339",
    "message": "Oi, pessoal da Equipe Fisioterapia Especializada. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a clínica pesquisando fisioterapia na Praia da Costa e preparei uma prévia de site pensando em uma comunicação mais clara para quem busca atendimento.\n\nO nome de vocês já passa uma ideia técnica. Um site próprio pode reforçar isso melhor: explicar a atuação, mostrar a região, deixar o telefone em destaque e facilitar o contato sem depender de diretórios.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/equipe-fisioterapia-especializada/\n\nNão é o modelo final. É uma base para vocês avaliarem. Posso ajustar linguagem, fotos autorizadas, serviços, prioridades, cores e informações confirmadas pela equipe.\n\nUsei informações públicas e uma imagem neutra. Não usei fotos de pacientes, imagens privadas ou promessas de resultado. A intenção é criar uma primeira impressão mais forte, mas ainda responsável.\n\nSe vocês gostarem da ideia, posso conversar sobre a clínica e montar uma versão final focada em transformar pesquisa local em conversa pelo WhatsApp.\n\nPosso te explicar como avançaríamos?"
  },
  "espaco-fisiovida": {
    "phone": "5527998469349",
    "message": "Oi, pessoal do Espaço FisioVida. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei o FisioVida pesquisando fisioterapia e pilates em Vila Velha e preparei uma prévia de site para mostrar como o espaço poderia aparecer melhor para quem procura pelo celular.\n\nA pessoa quer entender rápido se o local atende perto dela, quais serviços existem e como chamar. Uma página própria coloca isso em ordem e evita que o contato dependa só de publicações ou diretórios.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/espaco-fisiovida/\n\nNão é o modelo final. É uma proposta inicial. Posso ajustar texto, fotos, cores, serviços, horários, região e os pontos que vocês quiserem destacar.\n\nUsei apenas dados públicos e imagem neutra. Não usei fotos de pacientes, alunos, equipe ou promessas de resultado. A ideia é mostrar uma versão mais clara e comercial da presença online do FisioVida.\n\nSe fizer sentido, posso conversar com vocês e transformar essa prévia em um site com foco em contato pelo WhatsApp.\n\nPosso te explicar como funcionaria?"
  },
  "espaco-vitta-saude": {
    "phone": "552721421173",
    "message": "Oi, pessoal do Espaço Vitta Saúde. Tudo bem?\n\nSou Luiz, de Vitória. Encontrei o Vitta pesquisando pilates, fisioterapia e terapias em Jardim da Penha e fiz uma prévia de site para mostrar uma presença online mais direta.\n\nVocês têm uma proposta que precisa ser entendida rápido: modalidades, localização, rotina de atendimento e caminho para falar. Em vez de deixar isso espalhado, a página organiza tudo para a pessoa chegar ao WhatsApp com mais segurança.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/espaco-vitta-saude/\n\nNão é o modelo final. É uma primeira direção. Posso ajustar textos, fotos autorizadas, cores, serviços, ordem das seções e chamadas para combinar com a identidade do Espaço Vitta.\n\nUsei informações públicas e imagens neutras. Não usei fotos privadas, pacientes ou promessas de resultado. O foco é vender a clareza do atendimento e facilitar a decisão de contato.\n\nSe vocês gostarem da ideia, posso entender melhor as modalidades e transformar essa prévia em um site real, pronto para usar.\n\nPosso te explicar os próximos passos?"
  },
  "essencesaude": {
    "phone": "5527997796437",
    "message": "Oi, pessoal da EssenceSaúde. Tudo bem?\n\nSou Luiz, de Vitória. Encontrei a EssenceSaúde pesquisando negócios de saúde na região e preparei uma prévia de site pensando em cuidado integrativo, pós-operatório, terapias e contato pelo WhatsApp.\n\nEsse tipo de serviço precisa passar confiança antes da pessoa chamar. Uma página própria ajuda a explicar a proposta da EssenceSaúde, organizar informações e criar um caminho mais simples entre a pesquisa e a conversa.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/essencesaude/\n\nNão é o modelo final. É uma proposta visual inicial. Posso ajustar tom, textos, fotos autorizadas, serviços, cores, prioridades e tudo que fizer mais sentido para o posicionamento da EssenceSaúde.\n\nUsei apenas informações públicas e imagens neutras. Não usei fotos privadas, pacientes ou promessas de resultado. A intenção é mostrar uma comunicação mais profissional sem exagerar em promessa.\n\nSe fizer sentido, posso conversar com vocês, entender melhor o negócio e transformar a prévia em um site com mais força comercial e foco em agendamento.\n\nPosso te apresentar como seria esse trabalho?"
  },
  "evolucao-centro-de-saude": {
    "phone": "5527992444185",
    "message": "Oi, pessoal da Evolução Centro de Saúde. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Evolução em canais públicos e criei uma prévia de site para mostrar como serviços, localização e WhatsApp poderiam ficar mais claros para quem pesquisa na Praia da Costa.\n\nQuando o negócio oferece mais de uma frente de saúde, a página precisa organizar a informação para a pessoa não se perder. A prévia foi pensada para apresentar o centro, orientar o visitante e levar ao contato.\n\nA página está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/evolucao-centro-de-saude/\n\nNão é o modelo final. É uma base para avaliação. Posso ajustar fotos, textos, serviços confirmados, cores, destaques e a estrutura conforme a realidade da Evolução.\n\nUsei informações públicas e imagens neutras. Não usei fotos privadas, pacientes ou promessas de resultado. O objetivo é mostrar como um site próprio pode deixar o centro mais fácil de entender e chamar.\n\nSe vocês gostarem, posso conversar com vocês e transformar essa prévia em uma versão final, com foco em contato pelo WhatsApp.\n\nPosso te explicar como eu faria?"
  },
  "fisio-para-todos": {
    "phone": "5527981592656",
    "message": "Oi, pessoal da Fisio para Todos. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Fisio para Todos pesquisando fisioterapia em Vila Velha e preparei uma prévia de site para mostrar como vocês poderiam aparecer com mais clareza nas buscas locais.\n\nQuem procura fisioterapia pelo celular geralmente quer resolver a dúvida rápido: se atende na região, como chamar e quais informações básicas precisa saber antes do primeiro contato. Um site simples entrega isso melhor que dados espalhados.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/fisio-para-todos/\n\nNão é o modelo final. É uma proposta inicial para vocês avaliarem. Posso ajustar texto, imagem, cores, serviços, localização e qualquer detalhe que precise representar melhor a Fisio para Todos.\n\nUsei apenas informações públicas e uma imagem neutra. Não usei fotos de pacientes, fotos privadas ou promessas de resultado. A página foi pensada para transformar pesquisa em conversa.\n\nSe fizer sentido, posso entender melhor o atendimento de vocês e montar uma versão final com a cara do negócio.\n\nPosso te mostrar como seria esse ajuste?"
  },
  "fisiocorporis": {
    "phone": "5527999166692",
    "message": "Oi, pessoal da Fisiocorporis. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Fisiocorporis pesquisando fisioterapia e pilates em Itapuã e preparei uma prévia de site para vocês avaliarem.\n\nA ideia é simples: quando alguém procura pelo celular, a Fisiocorporis precisa aparecer de um jeito claro, com serviço, bairro e WhatsApp bem visíveis. Isso passa mais confiança do que depender só de rede social ou diretórios.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/fisiocorporis/\n\nNão é o modelo final. É uma primeira proposta. Posso ajustar textos, imagens, cores, serviços, horários e qualquer ponto que vocês queiram destacar.\n\nUsei dados públicos e imagens neutras. Não usei fotos de pacientes, fotos privadas ou promessas de resultado. O foco é mostrar como uma página própria pode ajudar a Fisiocorporis a receber contatos com menos atrito.\n\nSe vocês gostarem da direção, posso conversar sobre o negócio e transformar essa prévia em um site final, pronto para divulgar.\n\nPosso te explicar o formato do trabalho?"
  },
  "fisiohealth-clinica-fisioterapia-pilates": {
    "phone": "552730149801",
    "message": "Oi, pessoal da Fisiohealth. Tudo bem?\n\nSou Luiz, de Vitória. Encontrei a Fisiohealth pesquisando fisioterapia e pilates em Jardim Camburi e preparei uma prévia de site para mostrar como a clínica poderia organizar melhor sua presença online.\n\nQuem chega pelo celular precisa entender rápido a localização, as frentes de atendimento e o caminho para falar com vocês. Uma página própria coloca fisioterapia, pilates e contato em uma leitura mais objetiva.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/fisiohealth-clinica-fisioterapia-pilates/\n\nNão é o modelo final. É uma proposta inicial. Posso ajustar textos, serviços, fotos autorizadas, cores, ordem dos blocos e o que mais fizer sentido para a rotina da Fisiohealth.\n\nUsei informações públicas e imagens neutras. Não usei fotos privadas, pacientes ou promessas de resultado. A página foi pensada para vender clareza e facilitar a primeira conversa pelo WhatsApp.\n\nSe fizer sentido, posso conversar com vocês e transformar essa prévia em um site real, mais fiel à clínica e pronto para uso.\n\nPosso te explicar como seria?"
  },
  "fisiolife-saude-integrada": {
    "phone": "5527998737295",
    "message": "Oi, pessoal da FisioLife Saúde Integrada. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a FisioLife pesquisando fisioterapia e pilates em Vila Velha e montei uma prévia de site para mostrar uma versão mais clara da presença online de vocês.\n\nQuando a pessoa está na Praia das Gaivotas ou por perto, ela precisa bater o olho e entender: é o serviço certo, fica na região e dá para chamar pelo WhatsApp. Foi esse caminho que organizei na prévia.\n\nA página está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/fisiolife-saude-integrada/\n\nNão é o modelo final. É uma proposta visual. Posso mudar textos, fotos, cores, serviços, horários, destaques e a ordem das informações conforme vocês preferirem.\n\nUsei apenas informações públicas e imagem neutra. Não usei fotos privadas, pacientes ou promessas de resultado. A intenção é mostrar um site simples, com cara profissional e foco em contato.\n\nSe fizer sentido para vocês, posso entender melhor a rotina da FisioLife e transformar essa prévia em um site final para divulgação.\n\nPosso te contar como seria esse processo?"
  },
  "fisiomovi-pilates-fisioterapia": {
    "phone": "5527996622323",
    "message": "Oi, pessoal da FisioMovi Pilates e Fisioterapia. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a FisioMovi pesquisando pilates e fisioterapia em Praia de Itaparica e preparei uma prévia de site focada em agendamento pelo WhatsApp.\n\nA decisão de chamar costuma acontecer rápido. Se a página explica o serviço, mostra a região e deixa o botão de contato visível, a pessoa tem menos motivo para seguir procurando outra opção.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/fisiomovi-pilates-fisioterapia/\n\nNão é o modelo final. É uma primeira versão para vocês visualizarem. Posso ajustar textos, fotos, cores, serviços, detalhes de agenda e tudo que precisar ficar mais fiel à FisioMovi.\n\nUsei informações públicas e imagens neutras. Não usei fotos de pacientes, alunos, equipe ou promessas de resultado. O foco é mostrar um caminho mais direto entre busca e contato.\n\nSe vocês gostarem da proposta, posso conversar com vocês e montar uma versão final com identidade, conteúdo correto e WhatsApp bem posicionado.\n\nPosso te explicar como avançamos?"
  },
  "fisioterapeuta-robson-vaillant": {
    "phone": "5527995004601",
    "message": "Oi, Robson. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei seu nome pesquisando fisioterapia em Vila Velha e preparei uma prévia de site para mostrar como sua atuação poderia aparecer de forma mais profissional nas buscas locais.\n\nPara um profissional autônomo, uma página própria ajuda bastante: apresenta seu nome, região, contato e informações iniciais sem depender só de diretórios. A pessoa entende rápido quem é você e como chamar.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/fisioterapeuta-robson-vaillant/\n\nNão é o modelo final. É uma proposta inicial. Posso ajustar texto, foto, cores, serviços, abordagem, área de atendimento e qualquer detalhe que combine melhor com a sua rotina.\n\nUsei apenas informações públicas e imagem neutra. Não usei fotos de pacientes, fotos privadas ou promessas de resultado. A intenção é mostrar uma presença mais clara e pronta para WhatsApp.\n\nSe fizer sentido, posso conversar contigo e transformar essa prévia em um site real para divulgar seu atendimento.\n\nPosso te explicar como ficaria?"
  },
  "fisioterapiahd": {
    "phone": "5527999887148",
    "message": "Oi, pessoal da FisioterapiaHD. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a FisioterapiaHD pesquisando fisioterapia em Praia de Itaparica e preparei uma prévia de site para vocês avaliarem.\n\nQuem pesquisa pelo celular quer tirar dúvidas iniciais rápido: se atende na região, como entrar em contato e o que precisa saber antes de chamar. Um site próprio organiza isso melhor e deixa o WhatsApp mais evidente.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/fisioterapiahd/\n\nNão é o modelo final. É uma proposta visual inicial. Posso ajustar textos, fotos, cores, serviços, destaques e a forma de apresentar a FisioterapiaHD.\n\nUsei apenas informações públicas e imagem neutra. Não usei fotos de pacientes, conteúdo privado ou promessas de resultado. A página foi pensada para dar mais segurança a quem ainda está escolhendo onde chamar.\n\nSe vocês gostarem da ideia, posso entender melhor o negócio e montar uma versão final com foco em contato pelo WhatsApp.\n\nPosso te mostrar como funcionaria?"
  },
  "hiaskara-macedo-fisioterapia": {
    "phone": "5527998514520",
    "message": "Oi, Hiáskara. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei seu nome pesquisando fisioterapia em Itapuã e preparei uma prévia de site para mostrar como seu atendimento poderia aparecer melhor para quem procura pelo celular.\n\nUma página própria ajuda a pessoa a entender rápido quem atende, qual região cobre e como falar. Para profissional de saúde, isso passa mais confiança do que depender apenas de listagens públicas.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/hiaskara-macedo-fisioterapia/\n\nNão é o modelo final. É uma ideia inicial. Posso ajustar texto, foto, cores, serviços, forma de apresentação e todos os dados que você quiser confirmar.\n\nUsei apenas informações públicas e imagem neutra. Não usei fotos de pacientes, fotos privadas ou promessas de resultado. A intenção é mostrar um site simples, direto e com foco no primeiro contato.\n\nSe fizer sentido para você, posso conversar sobre sua rotina e transformar essa prévia em um site final para divulgar seu trabalho.\n\nPosso te explicar como seria?"
  },
  "merinha-braga-studio-pilates": {
    "phone": "5527997460066",
    "message": "Oi, Merinha. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei o Studio Pilates pesquisando opções na Praia da Costa e preparei uma prévia de site pensando em quem quer conhecer o espaço e chamar pelo WhatsApp.\n\nPilates é muito visual, mas a pessoa também precisa entender rápido localização, proposta e caminho para falar. Um site próprio organiza isso melhor do que deixar tudo dependendo apenas do Instagram.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/merinha-braga-studio-pilates/\n\nNão é o modelo final. É uma proposta inicial. Posso ajustar textos, fotos autorizadas, cores, horários, serviços e qualquer detalhe para combinar melhor com o studio.\n\nUsei informações públicas e imagem neutra. Não usei fotos de alunos, conteúdo privado ou promessas de resultado. A ideia é mostrar como o Studio pode passar mais confiança já no primeiro acesso.\n\nSe fizer sentido, posso conversar contigo e transformar essa prévia em um site real, com a identidade do Studio e foco em WhatsApp.\n\nPosso te mostrar como ficaria?"
  },
  "mover-saude-pilates-musculacao-terapeutica": {
    "phone": "5527999051156",
    "message": "Oi, pessoal da Mover Saúde Pilates e Musculação Terapêutica. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Mover Saúde pesquisando pilates e musculação terapêutica em Vila Velha e preparei uma prévia de site para vocês avaliarem.\n\nA proposta de vocês tem um diferencial que merece aparecer com clareza. Uma página própria ajuda a explicar as modalidades, mostrar a região do Centro e levar quem está interessado direto para o WhatsApp.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/mover-saude-pilates-musculacao-terapeutica/\n\nNão é o modelo final. É uma direção inicial. Posso ajustar texto, imagens autorizadas, cores, serviços, horários, ordem das seções e a forma de apresentar a Mover Saúde.\n\nUsei apenas dados públicos e imagens neutras. Não usei fotos de pacientes, alunos, equipe ou promessas de resultado. O objetivo é vender melhor a proposta sem exageros.\n\nSe fizer sentido, posso conversar com vocês e transformar essa prévia em um site final, mais completo e preparado para gerar contatos.\n\nPosso te explicar como avançaria?"
  },
  "movifisio-clinica-fisioterapia": {
    "phone": "5527999011358",
    "message": "Oi, pessoal da MoviFisio Clínica de Fisioterapia. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a MoviFisio pesquisando fisioterapia em Praia de Itaparica e preparei uma prévia de site para organizar melhor as informações da clínica.\n\nQuando os dados aparecem só em diretórios, o visitante pode ficar inseguro ou desistir rápido. Uma página própria ajuda a mostrar nome, localização, contato e próximos passos em um lugar só.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/movifisio-clinica-fisioterapia/\n\nNão é o modelo final. É uma proposta para vocês avaliarem. Posso ajustar textos, fotos autorizadas, serviços, cores, dados confirmados e tudo que precisar representar melhor a MoviFisio.\n\nUsei informações públicas e imagem neutra. Não usei fotos de pacientes, conteúdo privado ou promessas de resultado. A página foi pensada para facilitar a primeira conversa pelo WhatsApp.\n\nSe fizer sentido, posso conversar sobre a clínica e transformar essa prévia em um site real, mais confiável para quem chega pela busca.\n\nPosso te explicar melhor?"
  },
  "my-space-pilates-fisioterapia": {
    "phone": "5527988970058",
    "message": "Oi, pessoal da My Space Pilates e Fisioterapia. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a My Space pesquisando pilates e fisioterapia em Itapuã e preparei uma prévia de site para mostrar como vocês poderiam aparecer de forma mais clara.\n\nPara quem procura pelo celular, uma página própria ajuda a entender o serviço, confirmar a região e chamar pelo WhatsApp sem depender de informação espalhada. Foi isso que organizei na demonstração.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/my-space-pilates-fisioterapia/\n\nNão é o modelo final. É uma proposta inicial. Posso ajustar texto, fotos, cores, serviços, horários, botões e a ordem das seções conforme o funcionamento da My Space.\n\nUsei apenas informações públicas e imagem neutra. Não usei fotos de pacientes, alunos, equipe ou promessas de resultado. A intenção é mostrar uma presença mais profissional e fácil de chamar.\n\nSe vocês gostarem da ideia, posso conversar com vocês e transformar essa prévia em um site final, focado em WhatsApp.\n\nPosso te contar como funcionaria?"
  },
  "odontomax-clinica-odontologica": {
    "phone": "5527998114067",
    "message": "Oi, pessoal da Odontomax Clínica Odontológica. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Odontomax pesquisando atendimento odontológico em Vila Velha e preparei uma prévia de site para mostrar uma forma mais clara de apresentar a clínica.\n\nNa odontologia, a pessoa precisa sentir segurança antes de chamar. Um site próprio ajuda a organizar localização, WhatsApp, informações iniciais e identidade da clínica em uma página mais profissional.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/odontomax-clinica-odontologica/\n\nNão é o modelo final. É uma proposta inicial. Posso ajustar textos, fotos autorizadas, cores, serviços, chamadas e todos os dados que vocês quiserem confirmar.\n\nUsei apenas informações públicas e imagens neutras. Não usei fotos de pacientes, antes e depois, imagens privadas ou promessas de resultado. O foco é facilitar a primeira conversa com mais confiança.\n\nSe fizer sentido para vocês, posso transformar essa prévia em um site real, com a cara da Odontomax e foco em contato pelo WhatsApp.\n\nPosso te explicar a proposta?"
  },
  "respirar-pilates-fisioterapia": {
    "phone": "5527999503365",
    "message": "Oi, pessoal da Respirar Pilates e Fisioterapia. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a Respirar pesquisando pilates e fisioterapia em Santa Mônica e preparei uma prévia de site pensada para contato rápido.\n\nQuem busca pilates ou fisioterapia pelo celular geralmente quer uma resposta simples: onde fica, o que oferece e como agendar. A página própria coloca essas respostas antes do visitante desistir ou procurar outro lugar.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/respirar-pilates-fisioterapia/\n\nNão é o modelo final. É uma primeira versão para vocês avaliarem. Posso ajustar textos, fotos, cores, serviços, horários e tudo que precise ficar com a cara da Respirar.\n\nUsei informações públicas e imagem neutra. Não usei fotos de pacientes, alunos, equipe ou promessas de resultado. A intenção é mostrar uma comunicação mais direta e profissional.\n\nSe fizer sentido, posso conversar com vocês e transformar essa prévia em um site final, pronto para receber contatos pelo WhatsApp.\n\nPosso te mostrar como seria?"
  },
  "sr-pilates-fisioterapia": {
    "phone": "5527998212719",
    "message": "Oi, pessoal da SR Pilates e Fisioterapia. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a SR pesquisando pilates e fisioterapia na região da Cidade da Barra e preparei uma prévia de site para vocês.\n\nA região tem busca local, e quem pesquisa pelo celular costuma escolher a opção que explica melhor serviço, bairro e forma de contato. Um site próprio ajuda a SR a aparecer com mais clareza nesse momento.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/sr-pilates-fisioterapia/\n\nNão é o modelo final. É uma proposta visual inicial. Posso ajustar texto, fotos, cores, serviços, horários, área atendida e qualquer detalhe que vocês quiserem priorizar.\n\nUsei apenas informações públicas e imagem neutra. Não usei fotos de pacientes, alunos, equipe ou promessas de resultado. A ideia é mostrar um caminho mais profissional entre a busca e o WhatsApp.\n\nSe vocês gostarem, posso entender melhor a rotina da SR e transformar essa prévia em um site final para divulgação.\n\nPosso te explicar como eu faria?"
  },
  "studio-pilates-sabrina-braga": {
    "phone": "5527998251293",
    "message": "Oi, Sabrina. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei o Studio de Pilates Sabrina Braga pesquisando pilates, fisioterapia e massagem em Itapuã e preparei uma prévia de site para você avaliar.\n\nQuando alguém procura um studio pelo celular, a página precisa passar confiança rápido: mostrar o que você oferece, onde atende e como chamar. Um site próprio faz isso sem depender só de post ou bio.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/studio-pilates-sabrina-braga/\n\nNão é o modelo final. É uma proposta inicial. Posso ajustar textos, fotos autorizadas, cores, horários, serviços e todos os detalhes que façam sentido para o seu atendimento.\n\nUsei apenas dados públicos e imagem neutra. Não usei fotos de alunos, pacientes, equipe ou promessas de resultado. O objetivo é mostrar como seu studio poderia ter uma presença mais clara e pronta para WhatsApp.\n\nSe fizer sentido, posso conversar contigo e transformar essa prévia em um site real para divulgar o Studio.\n\nPosso te explicar como seria?"
  },
  "viafisio": {
    "phone": "5527992521125",
    "message": "Oi, pessoal da VIAFISIO. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a VIAFISIO pesquisando fisioterapia, pilates e massoterapia em Praia de Itaparica e preparei uma prévia de site para vocês.\n\nA marca de vocês já tem uma identidade forte. O site entra para organizar a primeira impressão: mostra os serviços, reforça a região e deixa o WhatsApp pronto para quem quer falar sem procurar em vários lugares.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/viafisio/\n\nNão é o modelo final. É uma proposta visual inicial. Posso ajustar textos, cores, fotos autorizadas, serviços, sequência das seções e tudo que fizer mais sentido para a VIAFISIO.\n\nUsei apenas informações públicas, a logo fornecida e imagem neutra. Não usei fotos privadas, pacientes ou promessas de resultado. A intenção é mostrar um site simples, bonito e mais vendedor.\n\nSe vocês gostarem da direção, posso conversar com vocês e transformar essa prévia em uma versão final focada em contato pelo WhatsApp.\n\nPosso te explicar os próximos passos?"
  },
  "vilafisio-fisioterapia": {
    "phone": "5527992058920",
    "message": "Oi, pessoal da VilaFisio Fisioterapia. Tudo bem?\n\nSou Luiz, da Grande Vitória. Encontrei a VilaFisio pesquisando fisioterapia e pilates em Itapuã e preparei uma prévia de site com a logo de vocês em destaque.\n\nA ideia é que quem chega pelo celular entenda rápido a proposta da VilaFisio, veja a região de atendimento e tenha um caminho direto para chamar no WhatsApp. Isso deixa a primeira impressão mais profissional do que depender só de rede social.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/vilafisio-fisioterapia/\n\nNão é o modelo final. É uma base para vocês avaliarem. Posso ajustar textos, cores, fotos, serviços, horários, ordem das seções e qualquer ponto que precise refletir melhor a clínica.\n\nUsei apenas informações públicas, a logo fornecida e imagem neutra. Não usei fotos privadas, pacientes ou promessas de resultado. A intenção é mostrar uma presença online mais clara e pronta para contato.\n\nSe fizer sentido, posso conversar com vocês e transformar essa prévia em um site final com a identidade da VilaFisio.\n\nPosso te explicar como seria esse trabalho?"
  },
  "viva-odontologia": {
    "phone": "552730261235",
    "message": "Oi, pessoal da Viva Odontologia. Tudo bem?\n\nSou Luiz, de Vitória. Encontrei a Viva em uma listagem pública e preparei uma prévia de site para mostrar como a clínica poderia ter uma presença própria mais clara.\n\nComo algumas informações de rede social estavam ambíguas, montei uma página neutra, com foco no que importa para quem pesquisa atendimento odontológico: confirmar que é a clínica de Vitória, ver localização e chamar com facilidade.\n\nA prévia está aqui:\n\nhttps://portifolio-luizfbm.com.br/demos/viva-odontologia/\n\nNão é o modelo final. É uma proposta inicial para vocês revisarem. Posso ajustar textos, fotos autorizadas, serviços, cores, endereço, WhatsApp e qualquer informação que precise ficar correta.\n\nUsei apenas informações públicas e imagem neutra. Não usei fotos de pacientes, conteúdo de outra cidade, antes e depois ou promessas de resultado. A página foi pensada para passar segurança antes do primeiro contato.\n\nSe vocês gostarem da ideia, posso conversar com vocês e transformar essa prévia em um site real para a Viva Odontologia.\n\nPosso te explicar como funcionaria?"
  }
};
